// Generated by Wrangler
interface Env {
	PORT: string;
	ENVIRONMENT: string;
	DATABASE_URL: string;
	JWT_SECRET: string;
	JWT_EXPIRES_IN: string;
	RAPIDAPI_KEYS: string;
	OPENAPI_API_KEY: string;
	PDF_PARSE_MODEL: string;
	PDF_PARSE_FALLBACK_MODEL: string;
	POSTMAN_API_KEY: string;
	POSTMAN_COLLECTION_UID: string;
	BREVO_API_KEY: string;
	BREVO_SENDER_EMAIL: string;
	BREVO_SENDER_NAME: string;
	NOTIFY_EMAIL: string;
}
